version: "3.7"

services:
    mysql:
        image: mysql:8.4.0
        volumes:
            - laravel-example-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        ports:
            - 3306:3306

volumes:
    laravel-example-data:
